name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "13 20 * * *"
  # Manual triggers with workflow_dispatch
  workflow_dispatch:
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        with:
          gist-id: ${{ secrets.GIST_ID }}
          github-token: ${{ secrets.GH_TOKEN }}
          wakatime-api-key: ${{ secrets.WAKATIME_API_KEY }}
